host: "0.0.0.0"
port: 8317
auth-dir: "~/.cli-proxy-api"
proxy-url: ""
api-keys:
  - "quotio-local-01F5A882-83B5-453B-A155-A85B74593578"
  - sk-xeWN18WFMMI6DSqFtin01T1f3ZQtVyv1
remote-management:
  allow-remote: false
  secret-key: "$2a$10$8MF7IKQn6pOGg3lUzFe8JevD9FAIsFiGzT8PTzVzKRbDyGMuElMIG"
  panel-github-repository: https://github.com/router-for-me/Cli-Proxy-API-Management-Center
debug: false
logging-to-file: false
usage-statistics-enabled: false
routing:
  strategy: "fill-first"
quota-exceeded:
  switch-project: true
  switch-preview-model: true
request-retry: 3
max-retry-interval: 30
oauth-model-alias:
  antigravity:
    - name: rev19-uic3-1p
      alias: gemini-2.5-computer-use-preview-10-2025
    - name: gemini-3-pro-image
      alias: gemini-3-pro-image-preview
    - name: gemini-3-pro-high
      alias: gemini-3-pro-preview
    - name: gemini-3-1-pro
      alias: gemini-3.1-pro-preview
    - name: gemini-3-flash
      alias: gemini-3-flash-preview
    - name: claude-sonnet-4-5
      alias: gemini-claude-sonnet-4-5
    - name: claude-sonnet-4-5-thinking
      alias: gemini-claude-sonnet-4-5-thinking
    - name: claude-opus-4-5-thinking
      alias: gemini-claude-opus-4-5-thinking
  kiro:
    - name: kiro-claude-sonnet-4-5
      alias: claude-sonnet-4-5-20250929
      fork: true
    - name: kiro-claude-sonnet-4-5
      alias: claude-sonnet-4-5
      fork: true
    - name: kiro-claude-sonnet-4
      alias: claude-sonnet-4-20250514
      fork: true
    - name: kiro-claude-sonnet-4
      alias: claude-sonnet-4
      fork: true
    - name: kiro-claude-opus-4-6
      alias: claude-opus-4-6
      fork: true
    - name: kiro-claude-opus-4-5
      alias: claude-opus-4-5-20251101
      fork: true
    - name: kiro-claude-opus-4-5
      alias: claude-opus-4-5
      fork: true
    - name: kiro-claude-haiku-4-5
      alias: claude-haiku-4-5-20251001
      fork: true
    - name: kiro-claude-haiku-4-5
      alias: claude-haiku-4-5
      fork: true
request-log: false
